### ISSUE TITLE
Class File

### ISSUE THREAD

**Issue by KanapongAiamtip** [MarkKh/Data-structures-and-Algorithms#1]
I think the class file is not necessary to upload your repositories because most people interested  .java file because in fact copy your code in repositories and run it will get the class file already I'm sure you're understandable in my opinion. and will make you look more pro than ever  Nice one to share your code to every one  to  your class mate

**Comment by MarkKh** [comment]
Thank you for your feedback. I will bring your feedback to improve my job.
